name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4", "4.0", head]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install bundler
      run: gem install bundler -v 2.4.22
      if: ${{ matrix.ruby == '2.7' || matrix.ruby == '3.0' }}
    - name: Bundle install
      run: bundle install
    - name: Setup project
      run: bundle exec appraisal install
    - name: Run tests for Rails 6.0
      run: bundle exec appraisal rails-6-0 rake test
      if: ${{ matrix.ruby == '2.7' || matrix.ruby == '3.0' }}
    - name: Run tests for Rails 6.1
      run: bundle exec appraisal rails-6-1 rake test
      if: ${{ matrix.ruby == '2.7' || matrix.ruby == '3.0' }}
    - name: Run tests for Rails 7.0
      run: bundle exec appraisal rails-7-0 rake test
      if: ${{ matrix.ruby == '3.0' || matrix.ruby == '3.1' || matrix.ruby == '3.2' || matrix.ruby == '3.3' }}
    - name: Run tests for Rails 7.1
      run: bundle exec appraisal rails-7-1 rake test
      if: ${{ matrix.ruby == '3.0' || matrix.ruby == '3.1' || matrix.ruby == '3.2' || matrix.ruby == '3.3' }}
    - name: Run tests for Rails 7.2
      run: bundle exec appraisal rails-7-2 rake test
      if: ${{ matrix.ruby == '3.1' || matrix.ruby == '3.2' || matrix.ruby == '3.3' || matrix.ruby == '3.4' }}
    - name: Run tests for Rails 8.0
      run: bundle exec appraisal rails-8-0 rake test
      if: ${{ matrix.ruby == '3.2' || matrix.ruby == '3.3' || matrix.ruby == '3.4' }}
    - name: Run tests for Rails 8.1
      run: bundle exec appraisal rails-8-1 rake test
      if: ${{ matrix.ruby == '3.3' || matrix.ruby == '3.4' || matrix.ruby == '4.0' }}
    - name: Run tests for Rails edge
      run: bundle exec appraisal rails-edge rake test
      if: ${{ matrix.ruby == '4.0' || matrix.ruby == 'head' }}
    - name: Upload coverage to Qlty
      uses: qltysh/qlty-action/coverage@v2
      if: ${{ matrix.ruby == '3.4' && !github.base_ref }}
      with:
        oidc: true
        files: coverage/.resultset.json

  standard:
    name: Run standard
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Setup project
        run: bundle install
      - name: Rake standard
        run: bundle exec rake standard
